# Generated by Django 2.1.4 on 2019-01-12 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0003_auto_20190112_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 12, 14, 2, 31, 702603, tzinfo=utc)),
        ),
    ]
