# Generated by Django 2.1.4 on 2019-01-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0004_userprofile_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_date',
        ),
    ]
