# Generated by Django 2.1.4 on 2019-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0005_remove_userprofile_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_fee', models.CharField(max_length=60)),
                ('images', models.ImageField(default='golf', upload_to='images')),
                ('description', models.TextField(default='please enter the tournament description here', max_length=300)),
                ('venue', models.CharField(default='entebbe golf club', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
