# Generated by Django 2.1.4 on 2019-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0007_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='play_type',
            field=models.CharField(choices=[('professional', 'professional'), ('Handicap', 'Handicap')], max_length=20, null=True),
        ),
    ]
