# Generated by Django 2.1.4 on 2019-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0008_bookingmodel_play_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='play_type',
            field=models.CharField(choices=[('professional', 'professional'), ('Handicap', 'Handicap')], default='professional', max_length=20, null=True),
        ),
    ]
