# Generated by Django 2.1.4 on 2019-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0009_auto_20190121_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='Handicaps',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], max_length=20, null=True),
        ),
    ]
