# Generated by Django 2.1.4 on 2019-01-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0010_bookingmodel_handicaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='Handicaps',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='men', max_length=20, null=True),
        ),
    ]
