# Generated by Django 2.1.4 on 2019-01-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0011_auto_20190127_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_id',
        ),
    ]
