# Generated by Django 2.1.4 on 2019-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0012_remove_userprofile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='customers_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
