# Generated by Django 2.1.4 on 2019-01-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0013_bookingmodel_customers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='customers_id',
        ),
    ]
