# Generated by Django 2.1.4 on 2019-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0014_remove_bookingmodel_customers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='play_levels',
            field=models.CharField(choices=[('professional', 'professional'), ('Handicap', 'Handicap')], default='professional', max_length=20, null=True),
        ),
    ]
