# Generated by Django 2.1.4 on 2019-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0015_bookingmodel_play_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='men_handicap',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='women_handicap',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
