# Generated by Django 2.1.4 on 2019-02-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0016_auto_20190201_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='women_handicap',
        ),
    ]
