# Generated by Django 2.1.4 on 2019-02-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproject', '0017_remove_bookingmodel_women_handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='women_handicap',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
