# Generated by Django 2.1.4 on 2019-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='marital_status',
            field=models.CharField(max_length=100),
        ),
    ]
