# Generated by Django 2.1.4 on 2019-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190122_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinformation',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('cohabiting', 'cohabiting')], max_length=100),
        ),
    ]
