# Generated by Django 2.1.4 on 2019-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190122_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='image',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to='media/profile_pic'),
        ),
    ]
