# Generated by Django 2.1.4 on 2019-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
