# Generated by Django 2.1.4 on 2019-01-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190123_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeePersonalInfo'),
        ),
    ]
