# Generated by Django 2.1.4 on 2019-01-24 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_bankinformation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenshipinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenshipinfo',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeePersonalInfo'),
        ),
    ]
