# Generated by Django 2.0.4 on 2019-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190124_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
